### ISSUE TITLE
Apache httpd change

### ISSUE THREAD

**Issue by icing** [igrigorik/istlsfastyet.com#101]
Apache httpd supports TLS dynamic record sizes for HTTP/2 connections since 2.4.18. See https://httpd.apache.org/docs/2.4/mod/mod_http2.html#h2tlscooldownsecs

Could you please update the table? Thanks!

**Comment by igrigorik** [comment]
Ah, missed that, thanks!

FWIW, "In deployments where connections can be considered reliable"... the wording doesn't feel right here - e.g. TCP is reliable, so I should always set this to 0. Maybe reuse language from and link to slow start after idle in TCP?

**Comment by igrigorik** [comment]
Resolved via https://github.com/igrigorik/istlsfastyet.com/commit/1d7c8eff0f470bd32eb0c026988310da5a279b33.
