### ISSUE TITLE
Always get grunt error

### ISSUE THREAD

**Issue by rugk** [igrigorik/istlsfastyet.com#110]
I've followed [this instructions](http://gruntjs.com/getting-started#working-with-an-existing-grunt-project) but actually it always ends up with an error:

```
grunt-exec@0.4.6 requires a peer of grunt@~0.4 but none was installed.
```

and when running `grunt`:

```
>> Error: File to import not found or unreadable: foundation/functions
>>        Parent style sheet: /var/www/.../istlsfastyet/scss/_settings.scss
>>         on line 9 of scss/_settings.scss
>> >> @import "foundation/functions";
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.
```

Running on Debian
NodeJS v5

**Comment by igrigorik** [comment]
Try `npm install --global gulp` before you compile. The site is based on WSK: https://github.com/google/web-starter-kit/blob/v0.6.1/docs/install.md

**Comment by rugk** [comment]
Still get the same error. Do I need to clone WSK before?

**Comment by igrigorik** [comment]
```
$> npm install -g bower
$> bower install
$> npm install grunt
$> grunt install
```

Should do the trick.
