### ISSUE TITLE
F5 BIG-IP Now Supports Dynamic Record Sizing

### ISSUE THREAD

**Issue by bamchenry** [igrigorik/istlsfastyet.com#114]
As of version 12.1.0 (18.May.2016 release), BIG-IP supports Dynamic Record Sizing.

https://support.f5.com/content/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ssl-administration-12-1-0/_jcr_content/pdfAttach/download/file.res/BIG-IP_System__SSL_Administration.pdf

**Comment by bamchenry** [comment]
Pull request 115.
https://github.com/igrigorik/istlsfastyet.com/pull/115

**Comment by igrigorik** [comment]
Merged, thank you!
