### ISSUE TITLE
NGINX for Windows supports dynamic TLS

### ISSUE THREAD

**Issue by itpp16** [igrigorik/istlsfastyet.com#121]
We've taken it in to beta https://twitter.com/nginx4Windows/status/741604796554174464
You can test it here https://nginx-win.ecsds.eu/
Expected public release between 3-5 days.

**Comment by itpp16** [comment]
Public version has been released, enjoy dynamic TLS !

**Comment by igrigorik** [comment]
@itpp16 getting invalid cert error when I try to visit the site :(

**Comment by itpp16** [comment]
We use our own root certificate, just import our root or accept our basic certificate.
Site can also be visited by plain http.

**Comment by igrigorik** [comment]
> We use our own root certificate, just import our root...

... I don't think that's a good idea :)

Either way, thanks for the heads up! I don't think there is anything actionable here, closing.
