### ISSUE TITLE
haproxy support http2

### ISSUE THREAD

**Issue by StarDuster** [igrigorik/istlsfastyet.com#124]
Haproxy ALPN support was implemented in 1.5-dev18 version.

Just add ```bind *:443 ssl crt /path/ alpn h2,http/1.1``` in ```frontend ``` section of config file to  enable http2 feature of haproxy.

Reference:
https://news.ycombinator.com/item?id=9022807

**Comment by igrigorik** [comment]
We do list HAProxy as supporting ALPN, see: https://istlsfastyet.com/#server-performance

**Comment by StarDuster** [comment]
Umm, I'm a bit confused that why mark HAProxy as 'no' in the 'HTTP/2' column?

**Comment by igrigorik** [comment]
@StarDuster ALPN is a TLS extension that allows client and server negotiate the protocol. HAProxy supports the ALPN negotiation but it does not understand HTTP/2.. for that it must (as of today) proxy to a server that speaks h2c. Hence no HTTP/2 checkbox.

For more, see: https://hpbn.co/transport-layer-security-tls/#application-layer-protocol-negotiation-alpn

**Comment by StarDuster** [comment]
Thank you for your explaining.
