### ISSUE TITLE
Cloudflare supports 0-RTT

### ISSUE THREAD

**Issue by Saturate** [igrigorik/istlsfastyet.com#141]
This is taken from my control panel:

![image](https://cloud.githubusercontent.com/assets/453018/23614978/29e84fce-0285-11e7-9944-281d567fafcc.png)

**Comment by igrigorik** [comment]
@grittygrease is that so?

**Comment by grittygrease** [comment]
It is now. I'll open a PR.

**Comment by Saturate** [comment]
Guess we can close this then? :-)

**Comment by igrigorik** [comment]
Yep!
