### ISSUE TITLE
Add entry for Caddy Server

### ISSUE THREAD

**Issue by hmhackmaster** [igrigorik/istlsfastyet.com#145]
Caddy is a "Fast, cross-platform HTTP/2 web server with automatic HTTPS" and seems to fit the bill for inclusion on the 'Server Performance' table.

More info: https://github.com/mholt/caddy & https://caddyserver.com

**Comment by igrigorik** [comment]
I'd be happy to take a PR for it! @hmhackmaster up for putting one together? :)

**Comment by mholt** [comment]
Note that Caddy's row will be nearly equivalent to Go's row except that Caddy's "OCSP Stapling" value will be Yes instead of Optional.

**Comment by igrigorik** [comment]
Resolved via https://github.com/igrigorik/istlsfastyet.com/pull/165
