### ISSUE TITLE
h2o: tls 1.3 support

### ISSUE THREAD

**Issue by jbergstroem** [igrigorik/istlsfastyet.com#147]
..added in the 2.2 branch; merged with https://github.com/h2o/h2o/pull/1204.

Should I PR this or wait for a non-beta release?

**Comment by igrigorik** [comment]
Do we have an eta for non-beta? /cc @kazuho

**Comment by johnp** [comment]
2.2.0 with TLS 1.3 draft-18 support was released on April 5th:  
https://github.com/h2o/h2o/releases/tag/v2.2.0

**Comment by igrigorik** [comment]
\o/ .. @jbergstroem @johnp willing to make a PR? :)

**Comment by kazuho** [comment]
@jbergstroem @igrigorik Oh! I have missed reading this issue. Thank you for your efforts. I am looking forward for the PR getting merged.
