### ISSUE TITLE
EdgeCast Networks support HTTP/2

### ISSUE THREAD

**Issue by dacbrown** [igrigorik/istlsfastyet.com#150]
EdgeCast Network now supports HTTP/2. Please update CDN table to represent this.  
https://www.verizondigitalmedia.com/blog/2017/04/http2-done-right/

**Comment by igrigorik** [comment]
Awesome, thanks for the heads up! Any chance you can put together a quick PR with a link to the announcement?

**Comment by dacbrown** [comment]
Hi Ilya, 

This is the only PR that we did for the launch of HTTP/2:
https://www.verizondigitalmedia.com/blog/2017/04/http2-done-right/
Please let me know if you need anything other than this. 

Regards, 
David

**Comment by igrigorik** [comment]
Closed via https://github.com/igrigorik/istlsfastyet.com/pull/153.
