### ISSUE TITLE
Missing bootstrap CDN and datatables CDN

### ISSUE THREAD

**Issue by fdellwing** [igrigorik/istlsfastyet.com#158]
Please add `bootstrapcdn.com` (Bootstrap and FontAwesome) and `cdn.datatables.net` (jQuery Datatables). Thanks!

**Comment by igrigorik** [comment]
Neither of those are general purpose CDNs, I don't think it makes sense to add them to the overview. That said, I'd love for someone to build a similar table for various resource/library hosting providers.
