### ISSUE TITLE
F5 Networks BIG-IP v14, TLS1.3 beta support

### ISSUE THREAD

**Issue by vsnine** [igrigorik/istlsfastyet.com#168]
Hello, 

F5 Networks recently released version 14 of the BIG-IP platform which includes some support for TLS1.3. They note that support for it is considered beta. The release notes for version 14 are available at this link: https://support.f5.com/kb/en-us/products/big-ip_ltm/releasenotes/product/relnote-bigip-14-0-0.html 

_**Support for TLS v1.3 (Internet-Draft 26 only)**
The BIG-IP system now supports IETF Internet-Draft 26 for Transport Layer Security (TLS) Protocol version 1.3. Because the BIG-IP system supports Internet-Draft 26 only, this support for TLS version 1.3 is considered to be in beta phase and is not meant to be deployed in production environments. A list of major differences from TLS version 1.2 is included in Internet-Draft 26, here: https://tools.ietf.org/html/draft-ietf-tls-tls13-26._

**Comment by igrigorik** [comment]
Awesome, thanks for heads up Josh! Would you be up for making a quick PR to reflect this?

**Comment by vsnine** [comment]
FYI, opened #169

**Comment by whalehub** [comment]
@igrigorik @vsnine The PR was merged so I think this issue can be closed now.

**Comment by igrigorik** [comment]
👍
