### ISSUE TITLE
Fastly now support TLS 1.3 and 0-RTT

### ISSUE THREAD

**Issue by Nooshu** [igrigorik/istlsfastyet.com#202]
There's information about it in their [documentation here](https://docs.fastly.com/products/tls-service-options#limitations-and-key-behaviors). You have to contact their support team to have them enabled, but they are supported.

Happy to open a PR if you agree with it being added.

**Comment by sudhirpatamsetti** [comment]
Here is the documentation link https://docs.fastly.com/en/guides/enabling-tls-1-3-through-fastly and blog post https://www.fastly.com/blog/tls13-available
