### ISSUE TITLE
AWS CloudFront supports TLS 1.3

### ISSUE THREAD

**Issue by sashee** [igrigorik/istlsfastyet.com#214]
Here's the news item: https://aws.amazon.com/about-aws/whats-new/2020/09/cloudfront-tlsv1-3-support/

**Comment by whalehub** [comment]
@sashee I think this issue was fixed with #215.

**Comment by The-Periodic-Table-Of-Elements** [comment]
yo

**Comment by sashee** [comment]
Yeah, it's fixed:)
