### ISSUE TITLE
Add node.js to the server listing

### ISSUE THREAD

**Issue by cyouden** [igrigorik/istlsfastyet.com#43]
I don't know about most of the fields, but I do know it supports SPDY via [node-spdy](https://github.com/indutny/node-spdy).

**Comment by gunta** [comment]
ALPN not supported yet tho.

**Comment by xiongchiamiov** [comment]
It [looks like](https://github.com/joyent/node/releases) v0.11 and v0.12 have had releases now.

**Comment by igrigorik** [comment]
Anyone willing to update the feature matrix? Ideally, with links to appropriate docs? :)

**Comment by igrigorik** [comment]
Added in https://github.com/igrigorik/istlsfastyet.com/commit/e77aa734bfe2328f33f2c2d62cf64d48ea080fe2, closing.
