### ISSUE TITLE
io.js?

### ISSUE THREAD

**Issue by brendanashworth** [igrigorik/istlsfastyet.com#61]
Hi there, I was wondering whether the Node.js fork [io.js](https://github.com/iojs/io.js) will be represented on the website section "Server Performance". From what the right guys have told me, the io.js latest release has support for all of the said categories.

I'd be up for a PR if this would be accepted.

**Comment by igrigorik** [comment]
I'd happy to add it to the list if someone puts together a PR with appropriate links, etc.

**Comment by brendanashworth** [comment]
Awesome, I'll send in a PR tomorrow.

**Comment by brendanashworth** [comment]
PR: #62. I guess discussion will be continued there!
