### ISSUE TITLE
Using CDN without SPDY

### ISSUE THREAD

**Issue by bitinn** [igrigorik/istlsfastyet.com#64]
One of the question I would like to see in FAQ, is whether using CDN without SPDY support on a SPDY-enabled site have significant negative impact on load time.

Consider this scenario: if we have a flickr like service, and we have X% users from China while our servers are in the US. Given many CDN don't have data centers in China, connections will be expensive. Can choosing CDN without SPDY cause the site to load slower than simply serving files through SPDY multiplexing?

**Comment by igrigorik** [comment]
Unfortunately this is not an "answerable" question, in the sense that there isn't a simple true/false answer to it. Rather, the performance will vary based on many factors: size of resources, connection quality (speed, latency, packet loss), etc. Your best bet here is to instrument your site, measure, and draw conclusions for your own case...
