### ISSUE TITLE
SPDY support in Bitgravity

### ISSUE THREAD

**Issue by gkoundinya** [igrigorik/istlsfastyet.com#70]
Is SPDY or HTTP2.0 supported in Bitgravity CDN?

**Comment by igrigorik** [comment]
Unfortunately not familiar with it, if you can find the right data, I'd be happy to add it to the list.

**Comment by gkoundinya** [comment]
I have contacted a guy from BitGravity(Tata Communications). He said currently there is no support but they are planning to support it in coming days.

**Comment by igrigorik** [comment]
That's great to hear! When/if you hear back from them with an official announcement, let me know!
