### ISSUE TITLE
How about Incapsula CDN

### ISSUE THREAD

**Issue by SiriusBits** [igrigorik/istlsfastyet.com#73]
Very comparable to Cloudflare but with better security.

https://www.incapsula.com/

**Comment by igrigorik** [comment]
I don't know enough about their infrastructure, but I'm willing to add them (and anyone else) to the list if someone is willing to get the right data in place.. If you're a customer, perhaps ping them and ask about their support for the features we care about?

**Comment by ZigZagIL** [comment]
Hi, shoot me an email to ofer at incapsula dot com

**Comment by igrigorik** [comment]
@ZigZagIL would you be up for making a pull with relevant update? :)

**Comment by igrigorik** [comment]
Closed via #81
