### ISSUE TITLE
Netscaler supports HTTP/2 - but only on recent versions

### ISSUE THREAD

**Issue by steveworkman** [igrigorik/istlsfastyet.com#76]
Citrix have recently released version 11 of Netscaler which has some HTTP/2 support http://docs.citrix.com/en-us/netscaler/11/system/http-configurations/configuring-http2.html

However, it's only applicable to certain bits of hardware, and it's very new, so I'm not sure it qualifies as being "supported".

Comments?

**Comment by igrigorik** [comment]
Thanks for the heads up. 

FWIW, not all Netscaler products supported SPDY either, but we do list it on the site today with SPDY mention. I think it's fine to update the current matrix with H2 mention and link it to the doc you shared above. 

_p.s. "The NetScaler appliance does not support the request prioritization functionality." -- sigh._

**Comment by steveworkman** [comment]
PR #88

**Comment by igrigorik** [comment]
Closed via #88.
