### ISSUE TITLE
MaxCDN OCSP Stapling

### ISSUE THREAD

**Issue by jdorfman** [igrigorik/istlsfastyet.com#77]
Hey Ilya,

MaxCDN now supports OCSP Stapling.  Working on the others.

Thanks!

**Comment by igrigorik** [comment]
Awesome news, thanks for the heads up! I can update the site.. QQ: do you have a link to any docs / announcements I should point to?

**Comment by jdorfman** [comment]
No problem.  We are putting a blog post together, should be done early next week.  I will update this issue with the link.  Thanks Ilya.

**Comment by jdorfman** [comment]
Hey @igrigorik our copywriter was busy this week and didn't get to finish, we will have something hopefully Monday.  Sorry for the delay!

**Comment by gibbiv** [comment]
Hey @igrigorik. Here is the link to our announcement for OCSP stapling support: https://www.maxcdn.com/blog/now-shipping-ocsp-stapling/

**Comment by igrigorik** [comment]
Thanks guys! Should be live now.
