### ISSUE TITLE
IIS 10.0 supports HTTP/2

### ISSUE THREAD

**Issue by martinsuchan** [igrigorik/istlsfastyet.com#80]
According to this blogpost IIS 10.0 on Windows 10 and upcoming Windows Server 2016 supports HTTP/2
http://blogs.iis.net/nazim/http-2-for-iis-in-windows-10-technical-preview

SPDY is most likely not supported, even Google dropped support for SPDY in favor for HTTP/2.

**Comment by igrigorik** [comment]
Good catch, thanks! Fixed in https://github.com/igrigorik/istlsfastyet.com/commit/78e33001fd31a4081b36ef641f8e35b1a2ae5d91.
