### ISSUE TITLE
Nginx config with HTTP/2 - istlsfastyet.com

### ISSUE THREAD

**Issue by xetorixik** [igrigorik/istlsfastyet.com#83]
Hi,

Please update the Nginx config with HTTP/2 support.
Seems as SPDY is still enabled in the Nginx configuration (https://github.com/igrigorik/istlsfastyet.com/tree/master/nginx). 

I'm curious to see what the ideal Nginx configuration is with HTTP/2.

Thanks,

Regards,

**Comment by igrigorik** [comment]
Switched to gh-pages + Cloudflare.
